# trabalhando com data e hora em Python
from datetime import date, datetime, time

print("-----------------------------------------------")
print("Exemplo 1: Obtendo a data")
hoje = date(2023, 7, 15)
print("Data de hoje:", hoje)

print("-----------------------------------------------")
print("Data atual do sistema")
atual = date.today()
print("Data atual:", atual)

print("-----------------------------------------------")
print("Data e hora")
agora = datetime.now()
print("Data e hora atual:", agora)
dataHora = datetime(2023, 7, 15, 14, 30, 0)
print("Data e hora especifica:", dataHora)
print("-----------------------------------------------")
print("Exemplo 2: Extraindo componentes da data e hora")
print("Ano:", agora.year)
print("Mês:", agora.month)
print("Dia:", agora.day)
print("Hora:", agora.hour)
print("Minuto:", agora.minute)
print("Segundo:", agora.second)
print("-----------------------------------------------")
print("Trabalhando com hora")
hora_especifica = time(14, 30, 0)
print("Hora especifica:", hora_especifica)
print("Hora:", hora_especifica.hour)
print("Minuto:", hora_especifica.minute)
print("Segundo:", hora_especifica.second)